name: Deploy project

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Clone repositories
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install packages
        run: npm i

      - name: Build the app
        run: ./scripts/staging-project-build.sh

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOSTNAME }}

      - name: Sync source code
        run: rsync -azP --delete build/ staging:/var/www/${{ secrets.PROJECT_NAME }}
