name: Docs
on:
  push:
    branches: [master]
  workflow_dispatch:
concurrency:
  group: ci-docs-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  generate:
    name: Generate docs
    runs-on: ubuntu-24.04

    permissions:
      contents: write # Required to commit generated CHANGELOG.md and readme.md

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Generate a changelog
        run: bgord-scripts/changelog-generate.sh

      - name: Print changelog
        run: cat infra/CHANGELOG.md

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v5
        with:
          branch: master
          commit_message: "docs: generate CHANGELOG"
          file_pattern: infra/CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate a README
        run: bgord-scripts/package-readme-generate.sh "${GITHUB_EVENT_REPOSITORY_NAME}"
        env:
          GITHUB_EVENT_REPOSITORY_NAME: ${{ github.event.repository.name }}

      - name: Print README
        run: cat readme.md

      - name: Commit readme.md
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v5
        with:
          branch: master
          commit_message: "docs: generate readme"
          file_pattern: readme.md
          token: ${{ secrets.GITHUB_TOKEN }}
