name: Healthcheck
on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
concurrency:
  group: ci-healthcheck-${{ github.ref }}
  cancel-in-progress: true
jobs:
  healthcheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repositories
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run healthcheck script
        run: ./bgord-scripts/healthcheck.sh "${{ secrets.PROJECT_NAME }}" "${{ secrets.BASIC_AUTH_PRODUCTION }}"

      - name: Notify on failure
        if: ${{ failure() && steps.run_healthcheck.outcome == 'failure' }}
        run: |
          curl -sS -X POST "https://lobbygow.bgord.dev/api/notification-send" \
            -H "Content-Type: application/json" \
            -H "bgord-api-key: ${{ secrets.LOBBYGOW_API_KEY }}" \
            --data "{\"kind\":\"error\",\"subject\":\"[${{ secrets.PROJECT_NAME }}] healthcheck\",\"content\":\"https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}\"}"
